- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: 
        file: vars/vpc_setup.txt

    - name: Create Vprofile VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        tenancy: default
        dns_support: yes
        dns_hostnames: yes
        state: "{{ state }}"
      register: vpcout

    #- debug:
    #    var: vpcout

    - name: Create Public Subnet 1 in Zone 1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        map_public: yes
        cidr: "{{ PubSub1Cidr }}"
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out

    #- debug:
    #    var: pubsub1_out

    - name: Create Public Subnet 2 in Zone 2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone2 }}"
        state: "{{ state }}"
        map_public: yes
        cidr: "{{ PubSub2Cidr }}"
        resource_tags:
          Name: vprofile-pubsub2
      register: pubsub2_out

    - name: Create Public Subnet 3 in Zone 3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone3 }}"
        state: "{{ state }}"
        map_public: yes
        cidr: "{{ PubSub3Cidr }}"
        resource_tags:
          Name: vprofile-pubsub3
      register: pubsub3_out

    - name: Create Private Subnet 1 in Zone 1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        map_public: yes
        cidr: "{{ PrivSub1Cidr }}"
        resource_tags:
          Name: vprofile-privsub1
      register: privsub1_out

    - name: Create Private Subnet 2 in Zone 2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone2 }}"
        state: "{{ state }}"
        map_public: yes
        cidr: "{{ PrivSub2Cidr }}"
        resource_tags:
          Name: vprofile-privsub2
      register: privsub2_out

    - name: Create Private Subnet 3 in Zone 3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone3 }}"
        state: "{{ state }}"
        map_public: yes
        cidr: "{{ PrivSub3Cidr }}"
        resource_tags:
          Name: vprofile-privsub3
      register: privsub3_out

    - name: Internet Gateway Setup
      ec2_vpc_igw:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        state: "{{ state }}"
        resource_tags:
          Name: vprofile-IGW
      register: igw_out

    - name: Setup Public Subnet Route Table
      ec2_vpc_route_table:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: Vprofile-pubRT
        subnets:
          - "{{ pubsub1_out.subnet.id }}"
          - "{{ pubsub2_out.subnet.id }}"
          - "{{ pubsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_out.gateway_id }}"  
      register: pubRT_out