- name: Setup Vprofile stack
  hosts: localhost 
  connection: local
  gather_facts: no
  tasks:
    - name: Import output_vars file
      include_vars:
        file: vars/output_vars

    - name: Import vprostacksetup file
      include_vars:
        file: vars/vprostacksetup.txt

    - name: Import vpc_setup file
      include_vars:
        file: vars/vpc_setup.txt

    - name: Create Vprofile EC2 Key-Pair
      ec2_key:
        name: vprokey
        region: "{{ region }}"
      register: vprokey_out

    - name: Save private key into loginkey-vpro.pem file
      copy:
        content: "{{ vprokey_out.key.private_key }}"
        dest: "./loginkey-vpro.pem"
        mode: 0600
      when: vprokey_out.changed

    - name: Create Security Group for Load Balancer
      ec2_group:
        name: vproELB-sg
        description: Allow port 80 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - to_port: 80
            from_port: 80
            proto: tcp
            cidr_ip: 0.0.0.0/0 
      register: vproELB_out

    - name: Create Security Group for Vprofile Stack 
      ec2_group:  
        name: vproStack-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - to_port: 80
            from_port: 80
            proto: tcp
            group_id: "{{ vproELB_out.group_id }}"

          - to_port: 22
            from_port: 22
            proto: tcp
            group_id: "{{ BastionSG_Id }}"
      register: vproStack-sg_out

    - name: Update Security Group with its own sg id
      ec2_group:
        name: vproStack-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{ vproStack-sg_out.group_id }}" 




